---
title: "Version Dropdown Menu"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Version Dropdown Menu}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

grkgdown replaces the pkgdown version number with a version dropdown menu
that allows users to switch between different versions of the package.

## Setup

There are three components to this feature:

1. We assume there is a single source of truth for all dropdown menus,
   stored in a file `doc-versions.json` in the root of your pkgdown site.

   Typically, this file is found in the `gh-pages` branch of your repo.
   You can store the file in `pkgdown/assets/doc-versions.json` so that it's
   copied automatically into your pkgdown site, but only the top-level versions
   file will be used. This way, older versions of the site will still be able to
   link to the latest release list.

   We'll talk about the format of this file in a moment.

2. You need to set up the build process for your pkgdown site
   in a way that keeps separate copies of the website for each version of the
   package.

   One way to do this is to use the
   [rstudio/education-workflows pkgdown action](https://github.com/rstudio/education-workflows/tree/main/examples#deploy-pkgdown-to-github-pages-with-pr-previews-and-tagged-versions).

3. The final bit is a JavaScript file that needs to be included after the body
   in the pkgdown template. grkgdown handles this automatically.

## Versions file

At its most simple the `doc-versions.json` file is a JSON file with a list of versions
as key-value pairs.

```json
{
  "v1.0.0": "https://pkg.garrickadenbuie.com/epoxy/v1.0.0/",
  "v0.1.1": "https://pkg.garrickadenbuie.com/epoxy/v0.1.1/",
  "v0.1.0": "https://pkg.garrickadenbuie.com/epoxy/v0.1.0/"
}
```

You can also include divider lines and headers
to structure the releases dropdown menu.
A divider is literaly the string `"---"`
and a header is any other string.
You'll need to format your `doc-versions.json` file as an array of objects.

```json
[
	{
		"latest": "https://pkg.garrickadenbuie.com/epoxy/",
	  "dev": "https://pkg.garrickadenbuie.com/epoxy/dev/"
	},
	"---",
	"Releases",
	{
		"v1.0.0": "https://pkg.garrickadenbuie.com/epoxy/v1.0.0/",
		"v0.1.1": "https://pkg.garrickadenbuie.com/epoxy/v0.1.1/",
		"v0.1.0": "https://pkg.garrickadenbuie.com/epoxy/v0.1.0/"
	}
]
```
